const PATHS = {
	login:"POST:/admin/login",
	categories:"GET:/categories",
	savePreference:"PUT:/user/preference",
	user:"GET:/user",
	preference:"GET:/user/preference",
	registerDevice:"POST:/device/register",
	verifyEmail:"POST:/user/email-verify",
	resendEmail:"POST:/user/resend-email-token",
	changePassword:"POST:/auth/change-password",
	events:"POST:/admin/events",
	weekEvents:"GET:/events/week",
	event:"GET:/event/:id",
	favorites:"GET:/favorites",
	saveFavorite:"POST:/favorite/:id",
	removeFavorite:"DELETE:/favorite/:id",
	matches:"POST:/events/matches",
	createGroup:"POST:/group",
	groups:"GET:/groups",
	group:"GET:/group/:id",
	members:"GET:/group/members/:id",
	joinGroup:"POST:/group/join/:id",
	leaveGroup:"DELETE:/group/leave/:id",
	deleteGroup:"DELETE:/group/:id",
	addEvent:"POST:/group/event",
	getGroupEvents:"GET:/group/events/:id",
	getGroupEvent:"GET:/group/event/:id",
	removeEvent:"DELETE:/group/event/:id",
	going:"POST:/group/event/going/:id",
	notGoing:"POST:/group/event/not-going/:id",
	createEvent:"POST:/event",
	updateEvent:"PUT:/event/:id"
}
export default PATHS;

